# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end

 platform :ios, '10.0'

 target 'iOS_Market' do
  use_frameworks!
  # Pods for iOS_Market
  pod 'ScrollableSegmentedControl', '~> 1.3.0'

end


